config/routes.rb
Depot::Application.routes.draw do
  get 'admin' => 'admin#index'

  controller :sessions do
    get 'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope "(:locale)" do
    resources :users
    resources :orders
    resources :line_items do
      member do
        post 'decrement'
      end
    end
    resources :carts
    get "store/index"
    resources :products do
      get :who_bought, :on => :member
    end
    root :to => 'store#index', :as => 'store'
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Depot</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body id="store">
  <div id="banner">
    <%= image_tag("rails.png",:size => "40x40") %>
    <%= @page_title || t('.title') %> 
    <%= form_tag store_path, :class => 'locale' do %>
      <%= select_tag 'set_locale',
      options_for_select(LANGUAGES, I18n.locale.to_s),
      :onchange => 'this.form.submit()' %>
      <%= submit_tag 'submit' %>
      <%= javascript_tag "$('.locale input').each(function() {$(this).hide();});" %>
    <% end %>

  </div>
  <div id="columns">
    <div id="side">
      <% if @cart %>
        <%= hidden_div_if(@cart.line_items.empty?, :id=> "cart") do %>
          <%= render @cart %>
        <% end %>
      <% end %>

      <a href="http://<%= ROOT_URL %>/"><%= t('.Home') %></a><br />
      <a href="http://<%= ROOT_URL %>/"><%= t('.questions') %></a><br />
      <a href="http://<%= ROOT_URL %>/"><%= t('.news') %></a><br />
      <a href="http://<%= ROOT_URL %>/"><%= t('.contact') %></a><br />
      <div id="time">
        <%= Time.now %>
      </div>
     <% if session[:user_id] %>
       <br />
       <%= link_to 'Orders', orders_path %><br />
       <%= link_to 'Products', products_path %><br />
       <%= link_to 'Users', users_path %><br />
       <br />
       <%= button_to 'Logout', logout_path, :method => :delete %>
     <% end %>
    </div>
    <div id="main">
      <%= yield %>
    </div>
  </div>
</body>
</html>